export type {
  Author,
  Category,
  Comment,
  CommentListResponse,
  CommentStats,
  CreateCategoryData,
  CreateCommentData,
  CreatePostData,
  GetCategoriesResponse,
  GetPostsParams,
  GetPostsResponse,
  PaginatedCategoriesResponse,
  Post,
  PostCategory,
  PostStatus,
  UpdateCategoryData,
  UpdatePostData,
} from '@/schemas/posts';

